var body0 = null
var body1 = null
var orig_texts = {}
var tran_texts = {}
var orig_htmls = {}
var tran_htmls = {}
var tmp_orig_tran = []  // 存放著之前用過（可能也修改過）、但後來沒再用到的翻譯。。。是不是也應該留存起來呢？但留存這個到後來會不會爆炸呢？
var translated = false
var path = window.location.pathname + window.location.search


var saved_terms = {}    // 用來保存可替換的詞語記錄，結構如下：
/*
saved_terms = {
    token#1 : [  // 以 token 為索引
        {第一種解釋},
        {第二種解釋},
        ...
    ]
    ...
}
*/

var syntax_results = {} // 用來保存各句的語法分析結果
/*
syntax_results = {
    sent_text#1 : {語法分析結果}
    ...
}
*/

dependencyDict = {
    'UNKNOWN':'？',
    'ABBREV':'縮寫', //修飾詞',
    'ACOMP':'形容詞補語',
    'ADVCL':'副詞子句', //修飾詞',
    'ADVMOD':'副詞飾詞', //'副詞修飾詞（狀語）',
    'AMOD':'形容名詞片語', //（NP）的形容詞修飾詞',
    'APPOS':'名詞片語同位飾詞',
    'ATTR':'隨連系動詞而異的定語？',
    'AUX':'助動詞', //（非主動詞）',
    'AUXPASS':'被動助詞',
    'CC':'並列連接詞',
    'CCOMP':'補語子句', //'做為某動詞或形容詞補語的子句',
    'CONJ':'連接詞',
    'CSUBJ':'主詞子句 ',
    'CSUBJPASS':'被動主詞子句',
    'DEP':'依賴（無法判定）',
    'DET':'限定詞',
    'DISCOURSE':'言談標記',
    'DOBJ':'直接受詞',
    'EXPL':'語助詞', //（感歎、咒罵）',
    'GOESWITH':'被切字', //（因為沒有處理好而只出現單詞的片段）',
    'IOBJ':'間接受詞',
    'MARK':'子句標記', //（引入從屬子句的單詞）',
    'MWE':'多字表達詞',
    'MWV':'多字表達動詞',
    'NEG':'否定飾詞',
    'NN':'複合飾詞', //'名詞複合修飾詞',
    'NPADVMOD':'副詞飾詞', //'名詞片語被用作副詞修飾詞',
    'NSUBJ':'主詞', //'名詞主語',
    'NSUBJPASS':'被動主詞', //'被動名詞主語',
    'NUM':'數量飾詞', //'名詞的數量修飾詞',
    'NUMBE':'複合數元素',
    'P':'標點符號',
    'PARATAXIS':'並列子句或片語', //'子句或片語前後並列，兩者之間沒有連接或表達其關係的詞，這樣的關係就叫做Parataxis關係',
    'PARTMOD':'分詞飾詞',
    'PCOMP':'介系詞補語', //'介系詞補語是子句？',
    'POBJ':'介系受詞',
    'POSS':'所有格', // 修飾詞',
    'POSTNEG':'否定助詞', //'動詞後的否定助詞',
    'PRECOMP':'謂詞補語',
    'PRECONJ':'前置連接詞',
    'PREDET':'前置限定詞',
    'PREF':'前綴',
    'PREP':'介系飾詞', //修飾詞',
    'PRONL':'動詞和動詞詞素之間的關係',
    'PRT':'助詞、虛詞',
    'PS':'聯合？或所有格標記',
    'QUANTMOD':'量詞片語飾詞',
    'RCMOD':'關係子句飾詞',
    'RCMODREL':'關係子句中的補語',
    'RDROP':'前面沒有謂詞的...省略符號',
    'REF':'參考',
    'REMNANT':'殘餘？',
    'REPARANDUM':'演講出錯但後來被講者修正的一個錯誤',
    'ROOT':'句根',
    'SNUM':'後綴指定數字單位',
    'SUFF':'後綴',
    'TMOD':'時間飾詞',
    'TOPIC':'主題標記',
    'VMOD':'不定詞子句', //'以動詞不定詞形式為首的子句，用來修飾名詞',
    'VOCATIVE':'呼格',
    'XCOMP':'開放子句補語？',
    'SUFFIX':'名稱後綴',
    'TITLE':'名稱標題',
    'ADVPHMOD':'副詞片語飾詞',
    'AUXCAUS':'使役助詞',
    'AUXVV':'輔助詞？',
    'DTMOD':'連體詞', //（名詞前修飾詞）',
    'FOREIGN':'外來詞',
    'KW':'關鍵詞',
    'LIST':'多串可比較項目列表',
    'NOMC':'名詞子句',
    'NOMCSUBJ':'名詞主詞子句', //'名詞子句主詞',
    'NOMCSUBJPASS':'被動名詞主詞子句', //'名詞子句被動？',
    'NUMC':'複合數量飾詞',
    'COP':'連系(動)詞',
    'DISLOCATED':'錯位關係', //（針對前置/專題化元素）？',
    'ASP':'動詞動態標記？',
    'GMOD':'所有格飾詞',
    'GOBJ':'所有格受詞',
    'INFMOD':'不定飾詞',
    'MES':'測量',
    'NCOMP':'名詞補語', //'名詞的名詞補語',
    /*
    '':'',
    'NE':'笑臉',
    'PART':'動詞查詢擴展',
    'APP':'交換',
    'NCL':'名詞名',
    'AJUCL':'動詞增強段落',
    'PARCL':'動詞動詞',
    'TAM':'傑出',
    'NPRT':'Nomenclature',
    'LVP':'組件',
    'NPP':'介詞數字',
    'VPRT':'當前表達',
    'COMPPP':'過度的參考詞',
    'ROOT':'#句根',
    'NPOSTMOD':'遲到的名字追踪',
    'NPREMOD':'前名字屬性',
    'PUNC':'書寫符號',
    'SBJ':'主題',
    'NVE':'當前',
    'ENC':'輔助動詞',
    'ADV':'#副詞',
    'NADV':'Nodid Name',
    'PRD':'主張',
    'ACL':'調整調整',
    'VCL':'動詞對齊',
    'AJPP':'加形容詞',
    'ADVC':'動詞形容詞',
    'NEZ':'增加形容詞',
    'PROG':'永久',
    'MOS':'mosand',
    'MOZ':'訂閱',
    'OBJ':'對象',
    'VPP':'可選的額外單詞',
    'OBJ2':'Second Item',
    'MESU':'審計',
    'AJCONJ':'形容詞',
    'PCONJ':'一起',
    'NCONJ':'基名',
    'VCONJ':'動詞的基礎',
    'AVCONJ':'沿著基地',
    'POSDEP':'延遲的子公司',
    'PREDEP':'以前的子公司',
    'APOSTMOD':'從屬形容詞',
    'APREMOD':'Previous屬性',
    */
  }
  
  tagDict = {
    'UNKNOWN':'？',
    'ADJ':'形容詞',
    'ADP':'介系詞',
    'ADV':'副詞',
    'CONJ':'連接詞',
    'DET':'限定詞',
    'NOUN':'名詞',
    'NUM':'數量詞',
    'PRON':'代名詞',
    'PRT':'助詞\虛詞',
    'PUNCT':'-', // '標點',  // 暫不標示
    'VERB':'動詞',
    'X':'X', // '其他',
    'AFFIX':'詞綴',
    /*
    '':'',
    '1':'第一',
    '2':'第二',
    '3':'第三',
    'ACT':'事實證明',
    'ADJ':'#形容詞',
    'ADR':'Neda的角色',
    'ADV':'#副詞',
    'AJCM':'詳細',
    'AJP':'絕對的',
    'AJSUP':'優秀',
    'AMBAJ':'模糊屬性',
    'ANM':'生活',
    'AVCM':'彙編',
    'AVP':'絕對',
    'AY':'前進意識',
    'CL':'因果',
    'COM':'詳細',
    'CONJ':'#連接詞',
    'CREFX':'共同的反思',
    'DEMAJ':'歸因屬性',
    'DEMON':'提示',
    'DET':'#限定詞',
    'EXAJ':'美妙的屬性',
    'GB':'不可預知的過去',
    'GBEL':'難以忘懷的過去',
    'GBES':'過去難以置信',
    'GBESE':'過去難以忍受',
    'GEL':'順從過去',
    'GES':'過去是一個連續的新聞',
    'GESEL':'一個持續的過去',
    'GN':'傳遞的新聞故事',
    'GNES':'過去是新聞的延續',
    'GS':'簡單過去簡單',
    'H':'現在這個消息',
    'HA':'現在',
    'HEL':'這是一個虛擬的',
    'IANM':'不朽',
    'IDEN':'索引',
    'INTG':'問題',
    'ISO':'一個字',
    'JOPER':'個人在線',
    'MODE':'臉',
    'MODL':'臉',
    'N':'名詞',
    'NUM':'#數量詞',
    'NXT':'左',
    'PART':'命令元素',
    'PASS':'未知',
    'PERS':'人',
    'PLUR':'複數',
    'POSADR':'晚',
    'POSNUM':'圖層符號',
    'POST':'絕對',
    'POSTP':'晚期介詞',
    'PR':'代詞',
    'PRADR':'previous',
    'PREM':'預定義',
    'PRENUM':'以前的形容詞',
    'PREP':'前面的單詞',
    'PRV':'從右',
    'PSUS':'偽句',
    'PUNC':'標點符號',
    'QUAJ':'查詢屬性',
    'RECPR':'十字',
    'SADV':'具體',
    'SEPER':'單獨分開',
    'SING':'單數',
    'SUBR':'依賴的角色',
    'SUP':'優秀',
    'UCREFX':'非反射性反射',
    'V':'動詞',
    'ROOT':'',
    */
  
  }
  